### ISSUE TITLE
SI: When Calculating Taxes with Discounts applied to the order you can get a divide by 0 error

### ISSUE THREAD

**Issue by mtrutledge** [HotcakesCommerce/hotcakes-commerce-core#136]
## Describe the bug
If your order has a total discount value greater than 0 and you do not have any items configured for a tax schedule you will receive a divide by 0 error on line 596 of the OrderCalculator.cs file.

`discount = totalOrderDiscounts / qty;`

A check for a qty == 0 needs to be done.

## Software Versions
- Hotcakes:  03.02.00

## To Reproduce
1. Make sure that Hotcakes is set as the tax provider and there are no tax schedules configured
2. Configure a product and do not set a tax schedule or tax exempt
3. Attempt to Apply a discount to the order via a subtotal promotion code
4. A 500 error will be thrown when the discount is applied and a divide by 0 error will be logged in the log4net file

## Expected behavior
A 500 error should not be thrown and the discount should be applied properly.

## Error log
**Note: Debug DLL's**
Please replace the current extension DLL's with the debug DLL's (if these are available with the release) and reproduce the error with the debug DLL's before pasting the error log.

Paste the error log that is related to this issue.

> 2018-07-11 17:28:49,659 [BEL-VDEV-MR2][Thread:42][FATAL] DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication - System.DivideByZeroException: Attempted to divide by zero.
   at System.Decimal.FCallDivide(Decimal& d1, Decimal& d2)
   at Hotcakes.Commerce.Orders.OrderCalculator.TaxItems(List`1 items, IAddress billingAddress, IAddress shippingAddress, Decimal totalOrderDiscounts) in c:\Work\HCC-core\Libraries\Hotcakes.Commerce\Orders\OrderCalculator.cs:line 596
   at Hotcakes.Commerce.Orders.OrderCalculator.TaxOrder(Order order) in c:\Work\HCC-core\Libraries\Hotcakes.Commerce\Orders\OrderCalculator.cs:line 533
   at Hotcakes.Commerce.Orders.OrderCalculator.Calculate(Order order) in c:\Work\HCC-core\Libraries\Hotcakes.Commerce\Orders\OrderCalculator.cs:line 95
   at Hotcakes.Commerce.HotcakesApplication.CalculateOrderAndSave(Order o) in c:\Work\HCC-core\Libraries\Hotcakes.Commerce\HotcakesApplication.cs:line 191
   at Hotcakes.Modules.Core.Controllers.CartController.AddCoupon() in c:\Work\HCC-core\Website\DesktopModules\Hotcakes\Core\Controllers\CartController.cs:line 452
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass48.<InvokeActionMethodFilterAsynchronouslyRecursive>b__41()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass48.<InvokeActionMethodFilterAsynchronouslyRecursive>b__41()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by hismightiness** [comment]
Both issues passed QA
