### ISSUE TITLE
Hotcakes.Web.Images.ShrinkImageFileOnDisk temp files doesn't get deleted

### ISSUE THREAD

**Issue by Shaahkral** [HotcakesCommerce/hotcakes-commerce-core#320]
Trying to use the software in environment having more than 100k products we got into the following issue. The problem is in the function
`public static void ShrinkImageFileOnDisk(string originalFile, string newFileName, int maxWidth, int maxHeight)
        {
            var tempFile = TempFiles.GetTemporaryFileInfo();
            var settings = new ResizeSettings(maxWidth, maxHeight, FitMode.Max, null);
            ImageBuilder.Current.Build(originalFile, tempFile.FullName, settings);

            if (File.Exists(newFileName))
            {
                File.SetAttributes(newFileName, FileAttributes.Normal);
                File.Delete(newFileName);
            }
            File.Copy(tempFile.FullName, newFileName);
        }`

The problem is that the tempFile is never got deleted which causes futher calls to ShrinkImageFileOnDisk fail with exception:
Method:Hotcakes.Web.TempFiles.GetTemporaryFileInfo
StackTrace:
Message:
System.ArgumentException: Unable to create temporary file: {0}The file exists.

   at Hotcakes.Web.TempFiles.GetTemporaryFileInfo()
   at Hotcakes.Web.Images.ShrinkImageFileOnDisk(String originalFile, String newFileName, Int32 maxWidth, Int32 maxHeight)
   at Hotcakes.Commerce.Utilities.ImageProcessing.ShrinkImage(String originalFile, String outputDirectory, Int32 maxWidth, Int32 maxHeight)

Hotcakes.Web.TempFiles.GetTemporaryFileInfo() uses system Path.GetTempFileName, and [MSDN](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.gettempfilename?redirectedfrom=MSDN&view=netcore-3.1#System_IO_Path_GetTempFileName) clearly states:
"_The GetTempFileName method will raise an IOException if it is used to create more than 65535 files without deleting previous temporary files_."

**Comment by hismightiness** [comment]
What version of Hotcakes is this?  I only ask because a more recent release does this for you on a scheduled basis.

**Comment by Shaahkral** [comment]
Ours is 3.2.1
Didn't check if scheduled clearance is present here,but it wouldn't solve
the problem any way,as sometimes we need to do a full update of all our
products.

**Comment by hismightiness** [comment]
How many products does your store have?  At which point (approximately) does this appear to break in your instance?

**Comment by Shaahkral** [comment]
It's a multi-portal project,there are roughly 140k products in total. The
actual point is hard to tell,as it depends on too many things,but
anyway,judging by the MDSN doc,it should happen when up to 65535 calls are
done to the function.
