### ISSUE TITLE
PayPal Payments Pro checkout fails except when logged on as Superuser.

### ISSUE THREAD

**Issue by gnossosp** [HotcakesCommerce/hotcakes-commerce-core#499]
## Sponsorship  

If this request requires additional support (e.g., such as direct email/phone/meeting/development),
I have the following interest in helping to [sponsor the effot via GitHub Sponsors](https://github.com/sponsors/UpendoVentures):    

- [ ] None, please continue to work for me for free :P  
- [ ] Absolutely, I get value out of this!  
- [ ] Maybe later  
- [@] I'm already a sponsor... Woot!  once.. a while ago..

## Please summarize your question in one sentence
PayPal Payments Pro Gateway succeeds while logged on as Superuser. Guest checkout or Registered user (Admin, GuestCheckout, Registered) fails.

## Give a more extended description
Not sure if this is a bug or just something broken with my particular installation.

DNN 09.13.04
HCC 3.8.1
 ## Superuser-
Can place orders and process PayPal Pro payments (sandbox) . Can process payments as well.

## Public- 
Checkout works, creates user account (guestcheckout role) and places order. Payment is not processed in PayPal Payments Pro. 
In Orders>Order Details> Payments the credit card can be used to update, refund etc. No error thrown.

Checkout/Public Error
UPDATE PAYMENT ERROR
the payment information you provided was not able to be processed. Please update your payment information and try again.

Payment Error from Hotcakes Orders>Order Details>Payments Module

Error

:: HCP_PPP_1001 - Unknown Payment Error: Object reference not set to an instance of an object. :: STACKTRACE - Stack Trace at Hotcakes.Payment.Gateways.PayPalPaymentsPro.<>c__DisplayClass12_0.b__0() at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Hotcakes.Payment.Gateways.PayPalPaymentsPro.Authorize(Transaction t) at Hotcakes.Payment.Gateways.PayPalPaymentsPro.ProcessTransaction(Transaction t)

Also in same module Credit Card can not be used. Throws Error.

Admin Log Errors:
bsoluteURL:/DesktopModules/Hotcakes/API/mvc/checkout/CleanCreditCard

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:b4e35d15-1354-4a1e-afd5-d444c84b5a66

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:eOQD12PytrMyKfLTBSLq2qPQGfQ=

Message:Padding is invalid and cannot be removed.

StackTrace:

   at System.Security.Cryptography.RijndaelManagedTransform.DecryptData(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode paddingMode, Boolean fLast)
   at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.StreamReader.Dispose(Boolean disposing)
   at System.IO.TextReader.Dispose()
   at Hotcakes.Modules.Core.Controllers.CheckoutController.DecryptStringFromBytes(Byte[] cipherText, Byte[] key, Byte[] iv)
InnerMessage:

InnerStackTrace:

Source:mscorlib

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: win8122

AbsoluteURL:/API/personabar/serversummary/GetUpdateInfo

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:7c96ff16-f8a3-4008-8c3a-14c082070501

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:j6x8yF4zcQqBjAL6yTlJEtoLEZs=

Message:The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

StackTrace:

   at System.Net.HttpWebRequest.GetResponse()
   at Dnn.PersonaBar.UI.Services.ServerSummaryController.GetJsonObject[T](String url)
   at Dnn.PersonaBar.UI.Services.ServerSummaryController.RetrieveUpdateUrl(CacheItemArgs args)
InnerMessage:The remote certificate is invalid according to the validation procedure.

InnerStackTrace:

   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)

## I loaded debugging files and tested both. (Site is on portal 4)
_Snippet of Guest Checkout that failed_

2024-11-05 07:41:20.488-08:00 [win8122][D:2][T:50][DEBUG] DNN.Trace - PageBase.Render End (TabId:110,https://DOMAIN.net/Default.aspx?TabId=110&language=en-US)
2024-11-05 07:41:20.738-08:00 [win8122][D:2][T:41][DEBUG] DNN.Trace - Container.ProcessModule Start (TabId:110,ModuleID: 87): Module FriendlyName: 'Hotcakes Checkout')
2024-11-05 07:41:20.738-08:00 [win8122][D:2][T:41][DEBUG] DNN.Trace - Container.ProcessModule Info (TabId:110,ModuleID: 87): ControlPane.Controls.Add(ModuleHost:ModuleContent)
2024-11-05 07:41:20.738-08:00 [win8122][D:2][T:41][DEBUG] DNN.Trace - ModuleControlFactory.LoadModuleControl Start (TabId:110,ModuleId:562): ModuleControlSource:DesktopModules/Hotcakes/Checkout/CheckoutView.ascx
2024-11-05 07:41:20.738-08:00 [win8122][D:2][T:41][DEBUG] DNN.Trace - ModuleControlFactory.LoadModuleControl End (TabId:110,ModuleId:562): ModuleControlSource:DesktopModules/Hotcakes/Checkout/CheckoutView.ascx
2024-11-05 07:41:20.754-08:00 [win8122][D:2][T:41][DEBUG] DNN.Trace - PortalModuleBase.OnInit Start (TabId:110,ModuleId:562): ASP.desktopmodules_hotcakes_checkout_checkoutview_ascx
2024-11-05 07:41:20.754-08:00 [win8122][D:2][T:41][DEBUG] DNN.Trace - PortalModuleBase.OnInit End (TabId:110,ModuleId:562): ASP.desktopmodules_hotcakes_checkout_checkoutview_ascx
2024-11-05 07:41:20.754-08:00 [win8122][D:2][T:41][DEBUG] DNN.Trace - Container.ProcessModule End (TabId:110,ModuleID: 87): Module FriendlyName: 'Hotcakes Checkout')
2024-11-05 07:41:20.785-08:00 [win8122][D:2][T:41][DEBUG] DNN.Trace - PortalModuleBase.OnLoad Start (TabId:110,ModuleId:562): ASP.desktopmodules_hotcakes_checkout_checkoutview_ascx
2024-11-05 07:41:20.801-08:00 [win8122][D:2][T:41][DEBUG] DNN.Trace - PortalModuleBase.OnLoad End (TabId:110,ModuleId:562): ASP.desktopmodules_hotcakes_checkout_checkoutview_ascx
2024-11-05 07:41:20.848-08:00 [win8122][D:2][T:41][WARN] DotNetNuke.Services.Localization.LocalizationProvider - Missing localization key. key:ControlTitle_.Text resFileRoot:/DesktopModules/Hotcakes/Checkout/App_LocalResources/CheckoutView threadCulture:en-US userlan:
2024-11-05 07:41:20.848-08:00 [win8122][D:2][T:41][DEBUG] DNN.Trace - PageBase.Render Start (TabId:110,https://DOMAIN/Default.aspx?TabId=110&action=paymenterror&language=en-US)

_Snippet of Checkout while logged on as Super User (success)_
2024-11-05 07:42:12.661-08:00 [win8122][D:2][T:55][DEBUG] DNN.Trace - PageBase.Render End (TabId:110,https://DOMAIN/Default.aspx?TabId=110&language=en-US)
2024-11-05 07:42:12.817-08:00 [win8122][D:2][T:26][DEBUG] DNN.Trace - Container.ProcessModule Start (TabId:110,ModuleID: 87): Module FriendlyName: 'Hotcakes Checkout')
2024-11-05 07:42:12.817-08:00 [win8122][D:2][T:26][DEBUG] DNN.Trace - Container.ProcessModule Info (TabId:110,ModuleID: 87): ControlPane.Controls.Add(ModuleHost:ModuleContent)
2024-11-05 07:42:12.832-08:00 [win8122][D:2][T:26][DEBUG] DNN.Trace - ModuleControlFactory.LoadModuleControl Start (TabId:110,ModuleId:562): ModuleControlSource:DesktopModules/Hotcakes/Checkout/CheckoutView.ascx
2024-11-05 07:42:12.832-08:00 [win8122][D:2][T:26][DEBUG] DNN.Trace - ModuleControlFactory.LoadModuleControl End (TabId:110,ModuleId:562): ModuleControlSource:DesktopModules/Hotcakes/Checkout/CheckoutView.ascx
2024-11-05 07:42:12.832-08:00 [win8122][D:2][T:26][DEBUG] DNN.Trace - PortalModuleBase.OnInit Start (TabId:110,ModuleId:562): ASP.desktopmodules_hotcakes_checkout_checkoutview_ascx
2024-11-05 07:42:12.832-08:00 [win8122][D:2][T:26][DEBUG] DNN.Trace - PortalModuleBase.OnInit End (TabId:110,ModuleId:562): ASP.desktopmodules_hotcakes_checkout_checkoutview_ascx
2024-11-05 07:42:12.832-08:00 [win8122][D:2][T:26][DEBUG] DNN.Trace - Container.ProcessModule End (TabId:110,ModuleID: 87): Module FriendlyName: 'Hotcakes Checkout')
2024-11-05 07:42:12.832-08:00 [win8122][D:2][T:26][WARN] DotNetNuke.Entities.Tabs.TabController - Unable to find tabId 65 of portal 2
2024-11-05 07:42:12.848-08:00 [win8122][D:2][T:26][DEBUG] DNN.Trace - PortalModuleBase.OnLoad Start (TabId:110,ModuleId:562): ASP.desktopmodules_hotcakes_checkout_checkoutview_ascx
2024-11-05 07:42:12.848-08:00 [win8122][D:2][T:26][DEBUG] DNN.Trace - PortalModuleBase.OnLoad End (TabId:110,ModuleId:562): ASP.desktopmodules_hotcakes_checkout_checkoutview_ascx
2024-11-05 07:42:18.176-08:00 [win8122][D:2][T:26][WARN] DotNetNuke.Services.Localization.LocalizationProvider - Missing localization key. key:ControlTitle_.Text resFileRoot:/DesktopModules/Hotcakes/Checkout/App_LocalResources/CheckoutView threadCulture:en-US userlan:
2024-11-05 07:42:18.176-08:00 [win8122][D:2][T:26][DEBUG] DNN.Trace - PageBase.Render Start (TabId:110,https://DOMAIN/Default.aspx?TabId=110&action=receipt&id=11f61611-f608-4317-8ba5-f2d627cbfe0f&language=en-US)
2024-11-05 07:42:18.176-08:00 [win8122][D:2][T:26][DEBUG] DNN.Trace - PageBase.IterateControls Info (TabId:110,ControlId: skinDocType)

## Steps to reproduce (if needed)
Buy Product and checkout in Hotcakes using PayPal Payments Pro (sandbox) and payment is processed when logged on as superuser.
Payment is not processed when using store as public.

## Other comments or remarks
I suspected my DNN installation had some kind of problem (maybe the TLS/SSL) 
I changed payment processor to Authorize.Net and it works fine in sandbox for public/guest checkout.

## Also
I also tested TLS/SSL at https://www.ssllabs.com/ssltest/analyze.html
Almost all tests positive "A" except:
DNS CAA	No (more info)
Session resumption (caching)	No (IDs assigned but not accepted)
ECDH public server param reuse	Yes
 
Also Re installed Hotcakes 3.8.1 extension.
All the pages have Inherit and Registered Users permissions.
All templates seem to be in place.

Thoughts and strategy to hopefully make this work.
Thanks

**Comment by gnossosp** [comment]
**EDIT- Solved issue by unchecking "Non Shipping Product" from product.**
Admin>Shipping>Flat Rate $0.00 enabled
Edit Product Disable "Non Shipping Product"
**New Bug?**
PayPal Payments Pro checkout fails with non=shipping checkbox enabled and not logged in as SU.
